
stages :
   - build
   - test

image: debian:stretch9

build-all:
   stage: build
   script:
      - apt-get update && apt install -y build-essential libmagic-dev file
      - make
   artifacts:
      paths:
         - rsfind
      
test-all:
   stage: test
   dependencies:
      - build-all
   script:
      - apt-get update && apt install -y libmagic-dev file
      - locale
      - bash test.sh
      
      
