
stages :
   - build
   - test

image: debian:stretch

build-all:
   stage: build
   script:
      - apt-get update && apt install -y build-essential libmagic-dev
      - make
   artifacts:
      paths:
         - rsfind
      
test-all:
   stage: test
   dependencies:
      - build-all
   script:
      - apt-get update && apt install -y libmagic-dev
      - bash test.sh
      
      
